In [1]:
!pwd

/mnt/storage-brno6/home/xstary1/raims


In [2]:
import numpy as np
%load_ext autoreload
%autoreload 2

import sys; sys.path.append("..")

from utils.model_evaluation import model_selection, load_predictions
from utils.visual_utils import plot_scores

In [4]:
kind="de_novo"

In [5]:
P_FOLDER = f"predictions/{kind}"

In [49]:
l_pred_indices_per_k, y_indices, X_intens = load_predictions("gpt2_embd300_auto", "hugg_val", P_FOLDER)
l_pred_indices_per_k_, y_indices_, X_intens_ = load_predictions("base_1", "spec_val", P_FOLDER)

In [7]:
y_indices[0], y_indices_[0]

(array([147,  67, 138, 298, 299, 113, 204, 279, 209,  63]),
 array([31., 29., 30., 16., 17., 28., 15., 14., 33., 27.]))

In [8]:
X_intens[0], X_intens_[0]

(array([1.        , 0.47304304, 0.40104104, 0.31303303, 0.29203203,
        0.26102102, 0.21402402, 0.08101101, 0.04900901, 0.008999  ,
        0.003003  ]),
 array([1.        , 0.47304304, 0.40104104, 0.31303303, 0.29203203,
        0.26102102, 0.21402402, 0.08101101, 0.04900901, 0.008999  ]))

In [30]:
l_pred_indices_per_k[10][0]

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1.])

In [18]:
l_pred_indices_per_k[23][300][X_intens[300][23:] > X_intens[300][23]*.2]

array([ 16., 297., 367., 366.,  23., 380.,  88.,  32.,   2.,  14.,  26.,
        57.])

In [28]:
y_indices[300][23:][:np.argmin(X_intens[300][23:] > X_intens[300][23]*.2)]

array([297,  16,  23, 367, 366,  57,  88, 121, 380,  32,  14,   2])

In [21]:
X_intens[300][23:] > X_intens[300][23]*.2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False])

In [23]:
np.argmin(X_intens[300][23:] > X_intens[300][23]*.2) 

12

In [18]:
k=0
to_rel_inten=.6
intens = np.array([1, .5, .3, .25, .20, .19, .15])
j = min(np.argmax(intens < intens[k]*to_rel_inten) - k - 1, 20)
if j ==-1:
    j=len(intens) - k -1
j

0

In [11]:
(l_pred_indices_per_k == -1).sum()

327860

In [28]:
l_pred_indices_per_k_[1][10]

array([ 44.,  29.,  58.,  12.,  14.,  86.,  40.,  60.,  30.,  88.,  18.,
        16.,  62.,  57.,  26., 116.,  27., 114.,  70.,  17.])

In [41]:
len(X_intens[433]), len(y_indices[433])

(32, 32)

In [54]:
for i, (inte, y) in enumerate(zip(X_intens,y_indices)):
    
    if len(inte) != len(y):
        print(len(inte), len(y))
        print(i)

113 112
28028


In [52]:
for i, (inte, idd) in enumerate(zip(X_intens,X_intens_)):
    
    if len(inte) != len(idd):
        print(len(inte), len(idd))
        print(i)

In [ ]:
for i, (y, idd) in enumerate(zip(y_indices,X_intens_)):


In [ ]:
class PredictionsTester():
    def __init__(self, P_FOLDER, d_name):
        self.P_FOLDER = P_FOLDER
        self.d_name = d_name
        
    def test(self):
        for (dirpath, dirnames, filenames) in os.walk(f"{self.P_FOLDER}/{self.d_name}/"):
            # if kw is not None:
            #     selected = [dirname for dirname in dirnames if kw in dirname]
            # if predictors is not None:
            #     selected = set(dirnames).intersection(set(predictors.keys()))
            for p_name in dirnames:
                print(p_name)
                l_pred_indices_per_k, y_indices, X_intens = load_predictions(p_name, d_name, P_FOLDER)

        def test_len(self, y_indices, X_intens):
            return all(map(lambda x,y: len(x)==len(y) zip(y_indices, X_intens)))
        
class MetricsTester():
    def __init__(self, )

In [48]:
len(y_indices)

28034